import accord

# A = accord.Enter()
A = ({1,2,3}, {3,4,5}, {(1,3),(2,4),(3,5)})
B = ({3,6,8}, {5,8,10}, {(3,5),(6,8),(8,10)})
print(A)
print(B)
U = accord.union(A, B)
print('Объединение:\n' + str(U))
C = accord.cross(A, B)
print('Пересечение:\n' + str(C))
D1 = accord.differense(A, B)
print('Разность Г1 и Г2:\n' + str(D1))
D2 = accord.differense(B, A)
print('Разность Г2 и Г1:\n' + str(D2))
S = accord.symmetric_differense(A, B)
print('Симметрическая разность Г1 и Г2:\n' + str(S))
I = accord.inversion(A)
print('Инверсия Г1:\n' + str(I))
C = accord.composition(A, B)
print('Композиция Г1 и Г2:\n' + str(C))
Con = accord.constriction(A)
print('Сужение на множество:\n' + str(Con))
if accord.continues(A) == False:
    print('Не является продолжением')
Imag = accord.imaginire(A)
print('Образ Г1 на множестве:\n' + str(Imag))
N_Imag = accord.neg_imaginire(A)
print('Пробраз Г1 на множестве:\n' + str(N_Imag))
